What: Try running tests using function host

diff --git a/.github/workflows/functionhost-ci.yml b/.github/workflows/functionhost-ci.yml
--- a/.github/workflows/functionhost-ci.yml
+++ b/.github/workflows/functionhost-ci.yml
@@ -42,7 +42,7 @@ env:
   DOMAINEVENT_LISTENER_CONNECTION_STRING: ${{ secrets.XDAST_DOMAINEVENT_LISTENER_CONNECTION_STRING }}
   # Variables that overrides settings in 'functionhost.settings.json'
   #DotnetExecutablePath: ''
-  FunctionAppHostPath: ''
+  FunctionAppHostPath: '${{ github.workspace }}\\node_modules\\azure-functions-core-tools\\bin\\func.dll'
   FunctionApplicationPath: '..\\..\\..\\..\\GreenEnergyHub.Charges.FunctionHost\\bin\\Release\\net5.0'
 
 jobs:
@@ -98,9 +98,15 @@ jobs:
       #   if: ${{ success() || failure() }}
       #   run: func --version
 
-      - name: Find node modules path
-        if: ${{ success() || failure() }}
-        run: npm root
+      # TODO: Remove when integration tests are working
+      # - name: Find node modules path
+      #   if: ${{ success() || failure() }}
+      #   run: npm root
+
+    - name: Test
+      shell: pwsh
+      run: |
+        dotnet test ${{ env.TEST_CSPROJ_FILE_PATH }} -p:CollectCoverage=true -p:CoverletOutput='${{ github.workspace }}/output/' -p:CoverletOutputFormat=cobertura -p:Threshold=0
 
       # - name: Build and test project
       #   uses: ./.github/actions/dotnet-build-and-test
