What: Test database manager

diff --git a/.github/workflows/functionhost-ci.yml b/.github/workflows/functionhost-ci.yml
--- a/.github/workflows/functionhost-ci.yml
+++ b/.github/workflows/functionhost-ci.yml
@@ -21,8 +21,8 @@ on:
 
 env:
   CSPROJ_FILE_PATH: source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj
-  #TEST_CSPROJ_FILE_PATH: source/GreenEnergyHub.Charges/source/GreenEnergyHub.FunctionApp.TestCommon.Tests/GreenEnergyHub.FunctionApp.TestCommon.Tests.csproj
-  TEST_CSPROJ_FILE_PATH: source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj
+  TEST_CSPROJ_FILE_PATH: source/GreenEnergyHub.Charges/source/GreenEnergyHub.FunctionApp.TestCommon.Tests/GreenEnergyHub.FunctionApp.TestCommon.Tests.csproj
+  #TEST_CSPROJ_FILE_PATH: source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj
   SOLUTION_FILE_PATH: source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln
   DOTNET_VERSION: '5.0.202'
   AZURITE_VERSION: '3.14.0'
@@ -72,18 +72,18 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@master # UNDONE: Why do we use version 'master' instead of a version tag? Using a branch is fragile.
 
-      # - name: Setup .NET 3.1 environment
-      #   uses: actions/setup-dotnet@v1
-      #   with:
-      #     dotnet-version: '3.1.x'
+      - name: Setup .NET 3.1 environment
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '3.1.x'
 
-      # - name: Setup .NET ${{ env.DOTNET_VERSION }} environment
-      #   uses: actions/setup-dotnet@v1
-      #   with:
-      #     dotnet-version: ${{ env.DOTNET_VERSION }}
+      - name: Setup .NET ${{ env.DOTNET_VERSION }} environment
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: ${{ env.DOTNET_VERSION }}
 
-      # - name: Install Azurite v${{ env.AZURITE_VERSION }}
-      #   run: npm install -g azurite@${{ env.AZURITE_VERSION }}
+      - name: Install Azurite v${{ env.AZURITE_VERSION }}
+        run: npm install -g azurite@${{ env.AZURITE_VERSION }}
 
       # - name: Install Azure Functions Core Tools v${{ env.AZURE_FUNCTIONS_CORE_TOOLS_VERSION }}
       #   run: npm install -g azure-functions-core-tools@${{ env.AZURE_FUNCTIONS_CORE_TOOLS_VERSION }}
@@ -104,20 +104,20 @@ jobs:
       #   run: npm root
 
       # TODO: Remove when integration tests are working
-      - name: Find docker images
-        if: ${{ success() || failure() }}
-        run: docker images
-      - name: Pull sql server
-        if: ${{ success() || failure() }}
-        run: docker pull mcr.microsoft.com/mssql/server:2019-latest
-      - name: Find docker images
-        if: ${{ success() || failure() }}
-        run: docker images
+      # - name: Find docker images
+      #   if: ${{ success() || failure() }}
+      #   run: docker images
+      # - name: Pull sql server
+      #   if: ${{ success() || failure() }}
+      #   run: docker pull mcr.microsoft.com/mssql/server:2019-latest
+      # - name: Find docker images
+      #   if: ${{ success() || failure() }}
+      #   run: docker images
 
-      # - name: Test
-      #   shell: pwsh
-      #   run: |
-      #     dotnet test ${{ env.TEST_CSPROJ_FILE_PATH }} -p:CollectCoverage=true -p:CoverletOutput='${{ github.workspace }}/output/' -p:CoverletOutputFormat=cobertura -p:Threshold=0
+      - name: Test
+        shell: pwsh
+        run: |
+          dotnet test ${{ env.TEST_CSPROJ_FILE_PATH }} -p:CollectCoverage=true -p:CoverletOutput='${{ github.workspace }}/output/' -p:CoverletOutputFormat=cobertura -p:Threshold=0
 
       # - name: Build and test project
       #   uses: ./.github/actions/dotnet-build-and-test
